sonar.projectKey=picun974_jarsentinel
sonar.organization=picun974
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.sourceEncoding=UTF-8
sonar.cpd.exclusions=src/test/**,src/main/java/org/jarsentinel/report/**,src/main/java/org/jarsentinel/detector/impl/**

